/**
 * ReportHistory Component
 * Lists prior report generation history.
 */
(function() {
    const ReportHistory = {
        render(containerId, history) {
            const el = document.getElementById(containerId);
            if (!el) return;

            if (!history || !history.length) {
                el.innerHTML = `
                    <div class="card glass-panel" style="padding:var(--space-6); text-align:center; color:var(--text-muted); font-size:11px;">
                        No reports logged in archive.
                    </div>`;
                return;
            }

            const listHtml = history.map(h => `
                <div style="padding:var(--space-3); background:rgba(9, 9, 11, 0.4); border:1px solid rgba(63, 63, 70, 0.3); border-radius:var(--radius-md); display:flex; flex-direction:column; gap:4px; margin-bottom:var(--space-2);">
                    <div style="display:flex; justify-content:space-between; align-items:center;">
                        <span style="font-size:10px; font-weight:700; color:#3b82f6;">${h.type}</span>
                        <code style="font-size:9px; color:var(--text-muted);">${h.id}</code>
                    </div>
                    <div style="font-size:9px; color:var(--text-muted);">
                        Generated by: <strong>${h.generated_by}</strong> on ${h.time.replace("T", " ")}
                    </div>
                    <div style="font-size:9px; color:var(--text-secondary); margin-top:2px; display:flex; justify-content:space-between; align-items:center;">
                        <span>Focus: ${h.template}</span>
                        <span style="color:#10b981;"><i class="fa-solid fa-download"></i> ${h.downloads} dl</span>
                    </div>
                </div>
            `).join("");

            el.innerHTML = `
                <div class="card glass-panel fade-in-slide-up" style="height:100%;">
                    <div class="card-header">
                        <h3><i class="fa-solid fa-clock-rotate-left text-primary"></i> Archive Library Logs</h3>
                    </div>
                    <div class="card-body" style="padding:var(--space-3); max-height:450px; overflow-y:auto;">
                        ${listHtml}
                    </div>
                </div>
            `;
        }
    };
    window.ReportHistory = ReportHistory;
})();
